// Command genslug writes internal/client/slug_tables.go, the data that makes client.Slugify match
// Home Assistant. Run it through scripts/gen-slug-tables.sh, which feeds it the tables from a
// Home Assistant container on stdin:
//
//	{"entities": {"amp": 38, ...}, "translit": ["\u0000", ..., "<text-unidecode of U+FFFF>"]}
//
// translit[cp] is text-unidecode's transliteration of code point cp. Only code points where
// go-unidecode disagrees are written out, as ranges sharing one transliteration.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"log"
	"os"
	"slices"

	"github.com/mozillazg/go-unidecode"
)

type tables struct {
	Entities map[string]int `json:"entities"`
	Translit []string       `json:"translit"`
}

type override struct {
	lo, hi int
	s      string
}

func main() {
	if len(os.Args) != 2 {
		log.Fatal("usage: genslug <output.go> < tables.json")
	}
	var t tables
	if err := json.NewDecoder(os.Stdin).Decode(&t); err != nil {
		log.Fatal(err)
	}

	var overrides []override
	for cp, want := range t.Translit {
		if cp < 0x80 || (cp >= 0xD800 && cp < 0xE000) || unidecode.Unidecode(string(rune(cp))) == want {
			continue
		}
		if n := len(overrides); n > 0 && overrides[n-1].hi == cp-1 && overrides[n-1].s == want {
			overrides[n-1].hi = cp
			continue
		}
		overrides = append(overrides, override{cp, cp, want})
	}

	var b bytes.Buffer
	b.WriteString("// Code generated by scripts/gen-slug-tables.sh; DO NOT EDIT.\n\npackage client\n\n")
	b.WriteString("// htmlEntities is Python's html.entities.name2codepoint: the HTML 4 named character\n")
	b.WriteString("// references that python-slugify decodes.\n")
	b.WriteString("var htmlEntities = map[string]rune{\n")
	for _, name := range slices.Sorted(func(yield func(string) bool) {
		for k := range t.Entities {
			if !yield(k) {
				return
			}
		}
	}) {
		fmt.Fprintf(&b, "%q: %#04x,\n", name, t.Entities[name])
	}
	b.WriteString("}\n\n")
	b.WriteString("// translitOverrides lists, sorted, the code points whose text-unidecode transliteration\n")
	b.WriteString("// (used by Home Assistant) differs from go-unidecode's.\n")
	b.WriteString("var translitOverrides = []translitOverride{\n")
	for _, o := range overrides {
		fmt.Fprintf(&b, "{%#04x, %#04x, %q},\n", o.lo, o.hi, o.s)
	}
	b.WriteString("}\n\n")
	fmt.Fprintf(&b, "// translitMax is the highest code point text-unidecode knows; it drops all others.\n")
	fmt.Fprintf(&b, "const translitMax = %#04x\n", len(t.Translit)-1)

	src, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile(os.Args[1], src, 0o600); err != nil {
		log.Fatal(err)
	}
}
